services:
  - type: web
    name: empresa-analitica
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_PUBLISHABLE_KEY
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: SUPABASE_JWKS_URL
        sync: false

  - type: web
    name: empresa-analitica-face
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.face
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: SUPABASE_PUBLISHABLE_KEY
        sync: false
